### Load NumPy

In [13]:
import numpy as np

### NumPy Array

In [14]:
a= np.array([1,2,3])
print(a)

[1 2 3]


In [15]:
b=np.array([[0.7,1.2,4.4],[0.9,3.5,9.8]])
print(b)

[[0.7 1.2 4.4]
 [0.9 3.5 9.8]]


In [16]:
# dimensions

adim=a.ndim
print(adim)
bdim=b.ndim
print(bdim)


1
2


In [17]:
# shape 

b.shape

(2, 3)

### Access

In [27]:
c = np.array([[1,2,3,4],[11,12,13,14]])
print(c)

[[ 1  2  3  4]
 [11 12 13 14]]


In [28]:
# get a specific element [r,c]
c[0,2]

3

In [30]:
# get a specific row
c[0,:]

array([1, 2, 3, 4])

In [31]:
# get a specific column
c[:,2]

array([ 3, 13])

In [32]:
# every other element
c[0,1:4:2]

array([2, 4])

### Replace

In [34]:
c[1,2]=7
print(c)

c[:,2]=20
print(c)

[[ 1  2  3  4]
 [11 12  7 14]]
[[ 1  2 20  4]
 [11 12 20 14]]


### Initializing different types of arrays

In [38]:
# all zeros

np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [41]:
# all ones 

np.ones((2,2), dtype='int32')

array([[1, 1],
       [1, 1]], dtype=int32)

In [40]:
# other number of choice 

np.full((3,3),8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [42]:
# random decimal numbers 

np.random.rand(3,3)

array([[0.06542049, 0.4623198 , 0.13766693],
       [0.60778548, 0.41497366, 0.87739784],
       [0.16533188, 0.75721292, 0.59300313]])

In [44]:
# random integer 

np.random.randint(10000, size=(3,3))

array([[ 636, 4782, 5958],
       [3652, 3761, 9115],
       [4416, 9310, 3772]])

In [45]:
# identity matrix 

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
# repeat 

array = np.array([[9,8,7]])
repeat=np.repeat(array, 5, axis=0)
print(repeat)

[[9 8 7]
 [9 8 7]
 [9 8 7]
 [9 8 7]
 [9 8 7]]


In [48]:
# lucky 7 

first=np.ones((5,5))
second=np.zeros((3,3))
second[1,1]=7
first[1:4,1:4]=second
print(first)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 7. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematics

In [49]:
# create NumPy array
d=np.array([1,2,3,4])
print(d)

[1 2 3 4]


In [50]:
# addition
d+2

array([3, 4, 5, 6])

In [51]:
# subtraction
d-0.5

array([0.5, 1.5, 2.5, 3.5])

In [52]:
# multiplication
d*2

array([2, 4, 6, 8])

In [55]:
# division
d/0.5

array([2., 4., 6., 8.])

In [56]:
# exponentiation
d**3

array([ 1,  8, 27, 64])

In [57]:
e=np.array([5,6,7,8])
print(e)

[5 6 7 8]


In [58]:
# addition of two arrays
d+e

array([ 6,  8, 10, 12])

In [59]:
# multiplication of two arrays
d*e

array([ 5, 12, 21, 32])

In [60]:
# subtraction of two arrays
d-e

array([-4, -4, -4, -4])

In [61]:
# exponentiation of two arrays
d**e

array([    1,    64,  2187, 65536])

In [62]:
# sin 
np.sin(d)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [63]:
# cos
np.cos(e)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

### Linear Algebra

In [69]:
f = np.ones((2,3))
print(f)
          
g = np.full((3,2),4)
print(g)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


In [70]:
np.matmul(f,g)

array([[12., 12.],
       [12., 12.]])

In [68]:
# determinant 
h=np.identity((3))
np.linalg.det(h)

1.0

### Statistics

In [71]:
statistics1=np.array(([4,8,12],[3,10,90]))
print(statistics1)


[[ 4  8 12]
 [ 3 10 90]]


In [72]:
# minimum value
np.min(statistics1)

3

In [73]:
# maximum value
np.max(statistics1)

90

In [74]:
np.max(statistics1, axis=1)

array([12, 90])

In [75]:
np.sum(statistics1)

127

In [76]:
#standard deviation
np.std(statistics1)

30.94304804349795

In [77]:
#variance 
np.var(statistics1)

957.4722222222222

### Reorganizing arrays

In [86]:
# reshape
before = np.array(([4,8,12,16],[3,10,90,120]))
print(before)

after=before.reshape((8,1))
print(after)

[[  4   8  12  16]
 [  3  10  90 120]]
[[  4]
 [  8]
 [ 12]
 [ 16]
 [  3]
 [ 10]
 [ 90]
 [120]]


In [89]:
# stacking vertically

a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
            
np.vstack([a1,a2,a1,a2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [91]:
# stacking horizontally 

b1=np.array([9,10,11,12])
b2=np.array([13,14,15,16])

np.hstack([b1,b2,b1,b2])

array([ 9, 10, 11, 12, 13, 14, 15, 16,  9, 10, 11, 12, 13, 14, 15, 16])

### Miscellaneous

In [98]:
# load .txt file 
file=np.genfromtxt('text.txt', delimiter = ',')
file=file.astype('int32')
file

array([  1,   2,   3,   4,   5,   6, 100,  22,  23,  45,  67,  89,  99,
        90,  87,  67,   1,   2,   3,   4,   5,   6, 100,  22,  23,  45,
        67,  89,  99,  90,  87,  67,   1,   2,   3,   4,   5,   6, 100,
        22,  23,  45,  67,  89,  99,  90,  87,  67,   1,   2,   3,   4,
         5,   6, 100,  22,  23,  45,  67,  89,  99,  90,  87,  67,   1,
         2,   3,   4,   5,   6, 100,  22,  23,  45,  67,  89,  99,  90,
        87,  67,  45], dtype=int32)

### Advanced indexing

In [101]:
file[file>20]


array([100,  22,  23,  45,  67,  89,  99,  90,  87,  67, 100,  22,  23,
        45,  67,  89,  99,  90,  87,  67, 100,  22,  23,  45,  67,  89,
        99,  90,  87,  67, 100,  22,  23,  45,  67,  89,  99,  90,  87,
        67, 100,  22,  23,  45,  67,  89,  99,  90,  87,  67,  45],
      dtype=int32)

In [102]:
# index with a list 
i=np.array([7,8,9,10,22])
i[[0,4]]

array([ 7, 22])

In [110]:
# boolean

np.any(file > 100, axis=0)

False

In [111]:
# two conditions

((file>10)&(file<90))

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True, False, False,  True,  True, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True, False, False,  True,  True, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
       False,  True,  True, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True, False, False,  True,
        True, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True, False, False,  True,  True,  True])

In [112]:
# reversed

(~((file>10)&(file<90)))

array([ True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False,  True,  True, False, False, False])

In [ ]:
# the end 